from exts import db
from models import Chapter
from config import ProdConfig
from main import create_app
from sqlalchemy.exc import IntegrityError

app = create_app(ProdConfig)

def seed_blurbs():
    print('seeding Blurbs')
    chapter1 = db.session.get(Chapter, 1)
    chapter1.video_blurb = "Welcome to the thrilling kickoff of our economics video series, 'Scarcity, Choice, and Opportunity Cost!' We know, we know — you're on the edge of your seat already. This is the first video of Introduction to Economic Concepts, so buckle up! It’s like the opening act at a concert, but instead of loud music, we’re here with something much better: cold, hard economics. Don’t worry, we’ll keep the math to a minimum… for now. \n\n In this video, we’ll guide you through the magical world where limited resources meet unlimited wants (spoiler alert: things get tricky). You'll learn about scarcity (aka, why you cannot have everything), choice (aka, why you have to make decisions, like choosing this video over cat memes), and opportunity cost (aka, the price of watching this video when you could have been napping). \n\n After the video, stick around for a quiz to show off your newfound econ knowledge. You know, just to make sure you're paying attention and not just here for our witty commentary. Go ahead, click play — your future self (and all the scarce resources) will thank you!"
    chapter1.quiz_blurb = "Congrats!  You've officially conquered your first EVTDS Video - Scarcity, Choice and Opportunity Cost!  Now it's time to take your first quiz, which is like a personality test from Cosmo but for Econ - are you more Econ 101 or The Wolf of Wall Street?  There are six questions - AP style -- so channel your inner economic mastermind and let’s see those skills in action!"
    chapter1.quiz_blurb_img_url = "https://evtds-seeds.s3.us-east-2.amazonaws.com/OCCartoon.png"

    chapter2 = db.session.get(Chapter, 2)
    chapter2.video_blurb = "Get ready to dive into the world of Factors of Production, where we’ll explore the essential ingredients for creating, well, pretty much everything. Land, labor, capital, and entrepreneurship — it’s like the recipe for an economic casserole. Spoiler: there’s no secret sauce, just a lot of work ... and some wonky definitions. \n\n Learn why land is not just about real estate, why labor is not just about suffering through your part-time job, and how entrepreneurs are basically the adventurous chefs of the economic world.  Just like chefs experiment with wild ingredients (Rocky Mountain Oysters anyone?), entrepreneurs toss around ideas that sometimes tase like gourmet meals and other times taste like... well, let's just say they might need more salt. \n\n Stick around after the video for a quiz, so you can prove you've mastered the art of economic cooking (or at least know your ingredients)! And if you manage to make a Fight Club version of the economic soup, not to worry, there's more review down the line!"
    chapter2.quiz_blurb = "Alright, you made it through Factors of Production—the thrilling world of land, labor, capital, and entrepreneurship! Now it’s quiz time. Brace yourself for questions that will ask if you really paid attention or if you were daydreaming about anything other than economic resources. Let’s see if all that ‘knowledge’ from the video stuck around long enough to help you out. Good luck!"
    chapter2.quiz_blurb_img_url="https://evtds-seeds.s3.us-east-2.amazonaws.com/FOP+Cartoon_2.png"
    
    chapter3 = db.session.get(Chapter, 3)
    chapter3.video_blurb =  "Hey there, economic adventurer! You’ve made it to Chapter 3, and things are really heating up. Welcome to <em>Economic Systems</em>: where we categorize the world's economies like a reality TV show judge. Capitalism, socialism, mixed economies — it's like choosing your favorite flavor of ice cream, but with more debates and fewer sprinkles. \n\n In this chapter, we’ll break down the pros and cons of each system, explaining why some countries have thriving free markets while others prefer the government to take the wheel. And hey, you might even discover which system suits your inner economist. \n\n Stay tuned for the quiz afterwards to see if you’re more Adam Smith or Karl Marx. It’s the ultimate personality test, econ style! Don’t worry, there are no wrong answers (except the wrong ones), and as always, it’s all in good fun. So grab your popcorn, sit back, and let’s figure out where you land on the economics spectrum!"
    chapter3.quiz_blurb = "Ready to test your knowledge of economic systems? By now, you probably know the difference between a Market Economy and that 'free' snack bar at work (spoiler: nothing’s really free). Dive into the quiz and let’s see if you’re ready to choose between capitalism, command, and a bit of both—or if you'll just end up with a mixed bag of guesses!"
    chapter3.quiz_blurb_img_url="https://evtds-seeds.s3.us-east-2.amazonaws.com/EconomicSystemsCartoon.png"
    
    chapter4 = db.session.get(Chapter, 4)
    chapter4.video_blurb = "Welcome to the thrilling world of the Production Possibilities Frontier, or as we like to call it, the ‘How Much Coconuts vs. Fish Can One Person Collect Before Losing Their Mind’ scenario. Imagine you’re a castaway, just you and the open sea. You’ve got two main goals: gather coconuts and catch fish, both essential for survival and maybe, just maybe, for bargaining with a volleyball named Wilson if things get lonely enough. But here’s the catch: every time you spend an hour hauling coconuts, that’s an hour you’re not fishing. Enter the Production Possibilities Frontier, the ultimate balancing act between making sure you don’t starve and maybe avoiding scurvy with those occasional coconuts. \n\nThis video will guide you through the delicate and riveting trade-offs of island economics, where you’ll start to think, “If only I had more hours in the day… or maybe a third arm.” And let’s be real, this concept might seem a bit ‘why am I learning this’ at first, but imagine the skills you’ll have if you’re ever stranded on a deserted island with only your AP Econ notes to keep you company. You’ll be ready to maximize your production and make life a little less miserable. \n\n So, sit back, take in the island vibes, and let’s figure out just how many coconuts you can collect before your fish stocks start to dwindle. Spoiler alert: the struggle is real. This is the survival story you didn’t know you signed up for, but trust us—you’ll be glad you’re equipped with some survival econ 101 if your plane ever takes an unexpected detour."
    chapter4.quiz_blurb_img_url = 'https://evtds-seeds.s3.us-east-2.amazonaws.com/PPFIslandCartoon.png'
    chapter4.quiz_blurb = "Alright, it's PPF time! Think of it like leveling up in a video game -- only instead of unlocking secret worlds, you're figuring out how many pizzas and tacos you can produce with limited resources. Possibility and growth are the name of the game here. Ready to quiz yourself and see if you're on the path to 'economic hero' or still in the tutorial level? No XP points, but hey, maybe a sense of accomplishment counts?"
    
    chapter5 = db.session.get(Chapter, 5)
    chapter5.video_blurb = "Welcome to <em>Production Possibilities Frontier: Part II</em>, where we dive deeper into the high-stakes drama of opportunity cost. Now, if you’ve sat through any sequels, you know there’s a mixed bag. <em>Back to the Future Part II</em>? Questionable.  <em>Speed 2: Cruise Control</em>? Hot Dumpster Fire - Jason Patric is a fine actor, but watching him fill Keanu's shoes was like watching someone try to run a marathon in flip flops.  But <em>The Godfather Part II</em>?  That's cinema. We’re aiming for a Godfather level here, breaking down why every choice you make on our deserted island means sacrificing something else. Yes, it's gritty, it's real, and you can leave your coconuts—and your dignity—at the door. \n\n Here's where things get interesting: in the real world (not on our fantasy island where we wish we were right now), producing more of something means producing less of something else.  In the sequel, the stakes are higher - it's not just about how much more you can produce-it's about what you're giving up in the process. Picture it: you're getting really good at fishing, but each hour casting a line means coconuts slipping through your fingers. And those coconuts? They represent every Saturday morning you’ve spent studying instead of sleeping in. That's the brutal reality of opportunity cost, and it hits harder than any disappointing sequel ever could. \n\n So, buckle up for Part II of the PPF, where you’ll learn that every fish, every coconut, every single decision carries a hidden cost. There’s no DeLorean to go back and fix your choices here—just cold, hard trade-offs and a lifetime supply of hypothetical coconuts."
    chapter5.quiz_blurb = "Look at you, making it through the PPF Part II like a true econ warrior.  Who knew you'd stick with it this long, almost as long as Taylor Swift's worldwide tour! \n\n This quiz is all about opportunity cost, but you already know a thing or two about sacrifice (like the last 15 minutes you could've spent literally anywhere else.)  You're so close to finishing this unit--it's practically waving at you from across the economic horizon, whispering the sweet, sweet siren song of freedom . . . or at least a short break."

    chapter6 = db.session.get(Chapter, 6)
    chapter6.video_blurb = "Alright, brace yourself: it’s time to dive into the world of Absolute and Comparative Advantage. No, it’s not a new Marvel movie, though it could be—after all, one is all about who’s got the bigger superpower (spoiler: it’s not always Robert Downey Jr.) You think being the best at something means you're automatically the one who should do it? Well, think again. This video will show you how even if you're the world's best at something, it doesn’t mean you’re <em>actually</em> the best person to do it. Sounds confusing? That's because it is... but in the best way possible. \n\n Forget about 'who’s better,' and start thinking about 'who’s least bad.' We’ll break down comparative advantage, where doing what you're least inefficient at might just be your golden ticket. So, get ready to rethink everything you thought you knew about trading, specialization, and making the most of your time—because economics has some real curveballs. And by the end of this, you might just feel like you’ve unlocked a cheat code to life-but probably not."
    chapter6.quiz_blurb = "Ready to prove you're the absolute expert on opportunity costs? Or will you get comparatively lost? Take this quiz to see if you truly understand why everyone can benefit from trade... or if you’re just trading in confusion. Spoiler alert: it's not as hard as it sounds, but don’t worry, even LeBron misses a shot every now and then (and Scotty misses a patch on the lawn!)"
    
    chapter7 = db.session.get(Chapter, 7)
    chapter7.video_blurb = "Ready to show the AP exam who’s boss? In this follow-up video, we're taking you from 'okay, I sort of get it' to 'I could teach this stuff!' We're diving into those tricky AP-style questions on Absolute and Comparative Advantage that always seem designed to make you question your life choices. But don’t worry—we've got your back. \n\n By the end of this video, you’ll be breezing through questions that make most people sweat like they just opened a textbook in front of the whole class. You'll learn how to spot the sneaky tricks that AP loves to throw at you, and how to tackle them like an econ pro. No more guessing or second-guessing—just straight-up strategy and the confidence that comes with knowing you've got this in the bag. Ready to make the AP exam your personal playground? Yeah, we thought so."
    chapter7.quiz_blurb = "Time to dive into a quiz that’ll have you comparing the number of hot dogs and hamburgers two people or countries can make in an hour. Because, of course, that's how we measure economic efficiency, right? Who cares about complex production systems when you can focus on the critical issue of who's the better grill master? The questions are absurd, the logic questionable, and the AP? Well, they sure know how to keep you on your toes. Good luck, and remember: it's not about who makes the most, it’s about who makes it with the most comparative advantage... even if it’s just in hot dog production."

    chapter8 = db.session.get(Chapter, 8)
    chapter8.video_blurb = "Ever notice how you <em>really</em> wanted to buy that life-sized gold statue of yourself… until you saw the price? Suddenly, it’s “maybe I’ll just get a nice framed photo.” That’s the Law of Demand in action—the idea that when prices go up, people decide they don’t actually need the 24-karat ego trip. It’s like how everyone wanted to own a Tesla... until they saw it costs about as much as a small island. Price has a magical way of turning “must-have” into “maybe I’ll pass.” \n\n In this video, we’re breaking down how the price of something can make you rethink your life choices. Think of it like hunting down rare, limited-edition sneakers or tickets Taylor Swift's concert—when the price is right, you feel like you have to have it, but raise it too much and suddenly you’re like, “I’m good, I’ll just stream it.” Once you get the Law of Demand, you’ll start seeing it everywhere, from your impulse buys to how much you’re willing to spend on a bottle of wine that tastes like regret. "
    chapter8.quiz_blurb = "Get ready to explore the wonders of the Law of Demand, where price and quantity are in a constant tug-of-war, <em>a la</em> episode 6 of <em>Squid Game</em>—except with less blood and more pizza. In this quiz, you’ll tackle the Income Effect (spoiler: it’s not just <em>‘mo' money, mo' stuff</em>) and the Substitution Effect—because when prices drop, you might ditch your usual soap for the one that smells like <em>freshly baked cookies and a hint of lavender</em>—even though they’re essentially the same. So, buckle up and get ready to decode why you're making questionable purchasing decisions based on price changes!"
    
    chapter9 = db.session.get(Chapter, 9)
    chapter9.video_blurb = "Welcome to the wild world of demand shifts — where nothing stays the same, and everything gets a little more complicated. If you thought demand only changes when prices do, well, surprise! Just like how The Office had a whole new vibe after Steve Carell left (no, it wasn’t the same, and we all know it), demand can shift due to all sorts of crazy factors.  We're talking about when substitute goods, like switching from Starbucks to Dunkin' because your local Starbucks is out of oat milk, or complement goods, like nachos and cheese, because who eats nachos alone? \n\nIn this video, we’ll cover the big players: normal and inferior goods, consumer preferences, and the demographic changes that make demand curve-shifting almost as dramatic as a plot twist in Game of Thrones (but hopefully with fewer disappointing outcomes). When people suddenly start loving avocado toast and stop buying… whatever the opposite of avocado toast is, that’s a shift in demand. It’s not just about price anymore — it’s about what's cool, what's not, and who’s influencing your decisions. \n\n So grab your popcorn and get ready to see how even the smallest changes in the market — from new trends to demographic shifts — can make demand go totally haywire. It’s like the world is always changing the channel, and the remote is out of reach. Just like those Fast and Furious movies that won’t stop at part 10, demand doesn’t know when to quit. "
    chapter9.quiz_blurb = "Welcome to the Shifting Demand quiz—where we figure out why people swap out perfectly good products for slightly different ones and why some things only make sense when they come in pairs. Ever traded your oat milk latte for a plain black coffee because your wallet tapped out? That’s a substitute good. Or maybe you’ve grabbed a pint of ice cream to go with your breakup binge-watch session—that’s complement goods in action. Economics, as it turns out, is just real life with fancy names. \n\n Remember, if demand can shift, so can your confidence—upwards, preferably. Substitutes and complements might sound like frenemies in a reality TV show, but they’re just your everyday choices wearing economics hats. Keep going, and who knows? You might just become the Beyoncé of shifting demand (and no, there are no substitutes for Beyoncé). Let’s do this!"
    
    chapter10 = db.session.get(Chapter, 10)
    chapter10.video_blurb = "Let’s talk about the law of supply, which is about as intuitive as trying to solve a Rubik’s Cube blindfolded. Essentially, the idea is simple: when prices go up, producers want to make and sell more. Sounds straightforward, right? But for some reason, this is where most econ teachers like to gloss over things or turn it into a maze of confusing explanations that leave you wondering if economics is secretly just a cruel joke. It’s counterintuitive, frustrating, and honestly, sometimes it just sucks. \n\n So why is it so confusing? Well, it doesn’t always make sense that the more expensive something is, the more of it people are willing to make. Isn’t that just... greedy? Exactly. It’s a strange concept, and it definitely feels like economics is out to make you feel dumb. But don’t worry — you’re not alone in thinking this is confusing, and you’re definitely not the only one who wishes you could just skip ahead to the part where economics gets <em>fun.</em>(This isn't fun?!?) \n\n Here’s the good news: by the end of this video, you’ll begrudgingly accept the law of supply as one of those things that <em>sort of</em> makes sense. I’m not saying you’ll love it, but you’ll get it, and that’s what really matters. So hang in there, we’ll pull this all together and make it clear enough that you can nod along and pretend you’re an economics expert."
    chapter10.quiz_blurb = 'Welcome to your quiz on Supply and the Law of Supply! Yes, we know—it sucked in the video, and guess what? It still sucks now. Upward-sloping curves, more supply at higher prices—it’s like economics took the scenic route just to confuse us. But hey, at least you’re not alone in thinking, <em>"Why is this a thing?"</em> \n\n  Here’s the good news: you don’t have to like it, understand it completely, or even pretend it makes sense. You just have to beat the quiz. Take a deep breath, channel your inner economics ninja, and tackle these questions one at a time. The law might suck, but your answers don’t have to. Let’s do this!'
    
    chapter11 = db.session.get(Chapter, 11)
    chapter11.video_blurb = "Ever wondered how Willy Wonka managed to crank out rivers of chocolate and entire forests of candy? It wasn’t just Oompa-Loompa magic—it was shifts to supply in action. Whether it’s a cocoa shortage, a sudden surplus of golden-ticket demand, or Wonka himself deciding to pivot to fizzy lifting drinks, the supply curve is constantly on the move. And don’t even get us started on Timothy Chalamet’s Wonka—some shifts just shouldn’t happen. \n\n This video breaks it all down, from the sweet simplicity of increased number of firms in the market to the bitter reality of increasing costs of factors of production. So grab your metaphorical golden ticket, watch the video, and then show off your new supply-shifting skills on the quiz. Just remember: real life might not be a candy-coated factory, but at least this part of economics is entertaining!"
    chapter11.quiz_blurb = "Welcome to the Shifts to Supply quiz! Shifting supply curves might feel like a cruel joke—why can’t they just stay put? But you’ve seen the video, so you know the drill: changes to costs of production, changes to number of firms in the market, taxes, subsidies, tigers and bears oh my! And we’re all left scrambling to figure out what’s going on.  \n\n Don’t overthink it—this quiz isn’t here to trick you (much). Keep calm, trust what you’ve learned, and take it one question at a time. Remember, even the messiest curve shifts have a right answer, and you’re more than capable of finding it. Let’s get started!"
    
    chapter12 = db.session.get(Chapter, 12)
    chapter12.video_blurb = "Welcome to the Supply and Demand in Equilibrium video! Think of this as the dystopian future of economics, starring <em>Empire of the Sun’s</em> Christian Bale, where shortages and surpluses are the villains trying to mess up the perfect balance. But don’t worry, just like in the movie, Equilibrium swoops in to save the day, restoring peace and order. \n\n In this world, supply and demand are <em>meant</em> to be in harmony, and when they’re not? Well, chaos ensues—kind of like when you accidentally buy 100 rolls of toilet paper during a panic buy. Watch the video to see how the market finds its perfect equilibrium and why it’s the ultimate happy ending for both buyers and sellers!"
    chapter12.quiz_blurb = "Welcome to the Supply and Demand in Equilibrium quiz! This is like finally finding that <em>perfect</em> parking spot at a Broncos game—you're cruising around, dodging chaos, and then <em>bam</em>, there it is: the ideal spot, right where you need it, not too far, not too close, just perfect. And like that perfect parking spot, when supply and demand hit equilibrium, everything clicks into place and the game can finally begin (without the stress of circling for hours). \n\n  You’ve got this! Sure, your favorite sports team might not always be in perfect equilibrium (looking at you, Bengals!), but you can definitely pull this off. Just like a game-winning play, take it one step at a time and trust your knowledge. Each question you answer brings you closer to that sweet, sweet victory. Keep going—you're on the right track!"
    
    chapter13 = db.session.get(Chapter, 13)
    chapter13.video_blurb = 'Hold onto your hats, because things are about to get wild! We’re diving into the epic world of supply and demand shifts-- You’ve been piecing together the clues this whole unit, and now, the big reveal is here. This isn’t just theory—it’s the ultimate culmination of everything you’ve learned, and just like those jaw-dropping twists you didn’t see coming, the changes in the market will leave you saying, “I didn’t know supply and demand could do that!” \n\n As we head towards the end of this unit, you’ll see how the concepts you’ve been mastering come together in ways that’ll have you questioning what you thought you knew about markets. It’s like you’ve been building up to the most mind-blowing plot twist of your economic journey—and now, it’s time to watch the magic unfold. It’s freaking amazing, and trust us—you’ll never look at price and quantity the same way again!'
    chapter13.quiz_blurb = 'Alright, you’ve made it this far—and everything you’ve learned up until now has been leading to this. This quiz isn’t just <em>any</em> quiz. No, this is the real deal. We’re talking about shifts in supply and demand, the concepts that will have you sounding like a genius on the AP exam. Everything you’ve done up to this point? Just the warm-up. This is the main event—the thing that’s going to come up <em>again and again</em> on the AP test. \n\n Think of this as the moment where all your hard work pays off. It’s the most important part of the unit, and if you can nail this quiz, you’ll be cruising through the rest of the course. So, take a deep breath, trust the process, and remember: you’ve got this. Everything you’ve learned? It’s all been leading to this one, crucial moment.'
    
    chapter14 = db.session.get(Chapter, 14)
    chapter14.video_blurb = 'Welcome to the world of <strong>simultaneous shifts to supply and demand</strong>--where things get confusing . . . but not really.  You’re about to dive into a market mess so complex that you’ll only know for sure if <em>price</em> or <em>quantity</em> changes at first. The other one? That depends on the magnitude of the shifts in both supply and demand. It’s like trying to predict the outcome of a battle between Godzilla and King Kong—you’re just not sure who’s going to win, but you know it’s going to be big. \n\n But here’s the thing—this is exactly how the real world works. Things are always changing. Markets are never static, and neither are we. Just when you think you’ve got a grip on everything, life throws a curveball. But hey, at least you’ll understand why prices and quantities shift like they do. It’s all part of the fun (and the chaos)! So strap in, embrace the confusion, and let’s figure out which way the market’s going to go!'
    chapter14.quiz_blurb = 'Alright, you’re about to face the <em>real</em> test of simultaneous shifts. Here’s the deal: when supply and demand shift together, you’ll know for sure if price or quantity changes. The other? Well, that depends on how far each curve shifts—kind of like knowing whether you’re getting extra cheese on your pizza, but not being sure if you’re also getting extra crust. It’s a mystery, but it’s a fun one! \n\n So get ready to dive in, think through the shifts, and prove you can handle the market’s little curveballs. You’ve got this!'

    chapter15 = db.session.get(Chapter, 15)
    chapter15.video_blurb = 'Time to dive into something that’ll really make you rethink how you see the world. Ever heard of <strong>diminishing marginal utility</strong>? It’s basically when the more you consume of something, the less excited you get about it. Think of it like eating your 7th rubber chicken at a medieval-themed dinner theater. The first one was kinda fun—by the 7th, you’re just wondering why you’re still holding onto this oddly chewy thing. That’s diminishing returns in action. \n\n Now, <strong>marginal benefit</strong> is related to <strong>marginal utility</strong>, but instead of measuring satisfaction in “utils” (which sounds like a weird currency from a sci-fi movie), we measure it in dollars—what people are willing to pay for each additional unit of something. So, the more of something you consume, the less you’re willing to pay for it. In other words, your marginal benefit starts to drop as your marginal utility drops. Pretty simple, right? \n\n But here’s the kicker: <em>the Demand Curve is the same thing as the Marginal Benefit Curve.</em> Wait, what? Yeah, it’s true. The amount a consumer is willing to pay for a good or service is reflected in the demand curve, which shows the marginal benefit of each additional unit consumed. It’s not magic—it’s just how economics works. \n\n So, pay close attention, and maybe rewatch it if you need to (like this season of The Bachelor, which you totally claim you don’t watch, but somehow find yourself rewatching the entire season... just saying). Once it clicks, you’ll never look at demand the same way again.'
    chapter15.quiz_blurb = 'Here’s the deal--just like with everything in life, there’s diminishing marginal benefit to taking quizzes. The first one? Exciting! The 10th? Maybe a little less thrilling. But guess what? You still need to take this one. \n\n If this is your FIRST time taking the quiz, there’s <strong>huge</strong> additional benefit to taking the quiz vs. not taking it!!  And hey, if you <em>failed</em> the first one, don’t worry.  The marginal benefit of the second quiz is still strong like bull!  You’ve learned from your mistakes, and the value of improving is real!  \n\n  Now, by the third, or fourth quiz?  Well...we can admit at this point enthusiasm is waning. Butvery quiz helps you get a little closer to mastery, even if you’re not jumping out of your seat with joy. So go ahead—take this quiz and reap the rewards. You’ve got this! '
    
    chapter16 = db.session.get(Chapter, 16)
    chapter16.video_blurb = 'Let’s dive into the world of <strong>marginal cost</strong> and <strong>supply</strong>. Imagine you’re running a hot dog stand—every time you make a new hot dog, you’re going to incur some cost, whether it’s for the dog, relish, or that random guy who keeps asking for a free sample. But here’s the thing: as you make more hot dogs, your marginal cost (the cost of producing one more unit) <em>might</em> go up as you run out of supplies or get more inefficient. And guess what? That affects your supply curve. \n\n At first, everything’s smooth sailing, but eventually, you might run out of supplies or need to hire extra help. That’s where the supply curve comes in: as the cost to produce more rises, producers are less willing to keep supplying at the same price. So, the higher the marginal cost, the higher the price needs to be for producers to keep making more. It’s like having to charge more for that hot dog to cover your growing costs. Simple? Sort of. But when you see it in action, it’s a bit mind-blowing. Stick with it, and the dots will connect. You might even start thinking about hot dogs a little differently.'
    chapter16.quiz_blurb = 'Time for your quiz on Marginal Cost and Supply.  We know, we know, you’ve been waiting since you signed up for this one.  Well it’s finally here.  You’re welcome.  \n\n Here’s the key: the supply curve is actually the marginal cost curve—yep, they’re the same! As marginal cost rises, producers are less willing to supply more unless they can charge higher prices. So, when you’re tackling this quiz, keep in mind that understanding this relationship is crucial. It’s not just about memorizing formulas; it’s about grasping how marginal cost determines how much gets supplied. Now go show off your knowledge!'

    chapter17 = db.session.get(Chapter, 17)
    chapter17.video_blurb = 'Imagine Clark Griswold, from National Lampoon’s Vacation, heading to buy a car. He’s ready to pay $50,000 for a new ride, but the car dealer gives it to him for $30,000. That’s consumer surplus—Clark gets more value than he paid for. Now, the seller would have been happy to sell at an even lower price, but they got $30k.  That’s producer surplus. Finally, social surplus is the total of both—Clark’s happy with the deal, and the seller’s raking it in. It’s the perfect win-win scenario for everyone involved. Watch the video to see how these surpluses work in real life and why they matter for the economy. Spoiler alert: it’s more than just Clark getting a great deal!'
    chapter17.quiz_blurb = 'You’ve learned how Clark, Marty and Ferris scored killer deals on their cars—and now it’s time to test your knowledge! Consumer surplus is what you get when you pay less than you’re willing to, producer surplus is the difference between what the producer needed to receive and what they actually got, and social surplus is the total benefit to both parties. These concepts are all over the AP exams, so it’s time to lock in those surpluses and show what you’ve got! Take a deep breath, ace this quiz, and keep driving toward that econ success. You’ve totally got this!'
    
    chapter18 = db.session.get(Chapter, 18)
    chapter18.video_blurb = 'Picture this: you’re ordering pizza for your Shark Tank Watch Party.  If you order too many pizzas, you’ll have leftovers that no one wants (and wast a lot of money) - the additional benefit of those extra pizzas is ZERO, and the additional cost is not zero.  Too much pizza.  If you order too few, you’ll run out and leave everyone hungry and grumpy -- talk about a disaster.  The additional benefit of having happy and full guests and playing the gracious host would have greatly outweighed the cost of shelling out a few more bucks for adequate grub. <strong>Allocative Efficiency</strong> is like getting the perfect number of pizzas where <strong>Marginal Benefit(MB) = Marginal Cost (MC)</strong>--the sweet spot where everyone’s satisfied and no pizza goes to waste. \n\n It’s like when you binge watch an entire season of <em>The Shield</em> in one sitting - you think you’re maximizing enjoyment, but the next day you’re left with regrets.  Watch this video to get that pizza quantity just right, and keep the good times rolling!'
    chapter18.quiz_blurb = 'Welcome to the quiz on Allocative Efficiency.  In this quiz, you’ll explore the concept of maximizing social surplus by finding the point where <strong>Marginal Benefit (MB) = Marginal Cost (MC)</strong>. It’s all about striking the right balance—too much of something wastes resources, and too little leaves people wanting more. This is a core microeconomics concept, and understanding it will help you nail down the foundation of how markets work. You’ve got this—just focus on the details and you’ll be ready for the next chapter!'

    chapter19 = db.session.get(Chapter, 19)
    chapter19.video_blurb = 'You know when the price of your favorite snack goes up, and suddenly, you find yourself asking, “Do I really need these pickled mangoes right now?” That’s Price Elasticity of Demand (PED) in action! It’s all about how much people’s willingness to buy changes when the price changes. Some products, like designer handbags or limited-edition sneakers, are super sensitive to price changes—raise the price just a little, and suddenly, the demand plummets. But other products, like toothpaste or your Monthly Mystery Tackle Box subscription, might not even budge in demand when prices increase. In other words, how much does a change in price make you go from must-have to meh? \n\n In this video, we’ll break down <strong>elastic</strong> vs. <strong>inelastic</strong> goods. Some things face elastic demand—a small price increase makes people think twice about buying. But demand for other things, like medicine or rent, is inelastic—people will pay the price, even if it stings a little. Businesses use this info to figure out how much they can increase prices before they start losing customers. You’ll learn how to spot which items are which, and trust me, it’s way more useful than knowing the secret ingredients to your favorite pizza place. \n\n This is important stuff for the AP exam, so make sure to rewatch if needed, and let’s get this elasticity thing under control!'
    chapter19.quiz_blurb = 'Quiz time for Price Elasticity of Demand.  Look, we know "elasticity" sounds like something you’d learn in a yoga class, but trust us, it’s important. The more you practice, the better you’ll get at it—like learning to make coffee that doesn’t taste like regret. So, take a deep breath, flex your brain muscles, and get through this. It’s not that hard, but if it is, well... maybe you should have paid attention in the video. Keep up the good work. You got this... probably.'
    
    chapter20 = db.session.get(Chapter, 20)
    chapter20.video_blurb = 'Why do some goods have elastic demand, while others could practically charge your soul and still keep selling? Welcome to the determinants of price elasticity of demand, where the answers are equal parts logic and frustration. Necessities like insulin? Inelastic. You can’t just choose not to buy it. Fancy avocado toast? Elastic. Swap it for a bagel, and no one cries. And let’s not forget time—give people long enough, and they’ll find a way to cut back on <em>anything</em>, even their streaming subscriptions (bye-bye, overpriced HBO Max). \n\n This video dives into why we treat some goods like irreplaceable treasures and others like yesterday’s leftovers at the smallest of price increases. You’ll never look at your shopping cart the same way again. Watch it, learn something, and then take the quiz—you might even figure out how to justify your iced coffee habit while you’re at it.'
    chapter20.quiz_blurb = 'Welcome to the Drivers of PED Quiz!  You’re guaranteed to get a question on the AP exam about what <em> causes </em> a good to face more or lest elastic dmeand.  And guess what? There’s <em>zero</em> math involved here! That’s right—just pure, unfiltered ideas. Finally, a part of economics where you can leave your calculator in your backpack and focus on thinking instead of crunching numbers. \n\n But don’t get too comfortable. Elasticity might seem straightforward, but it’s also a master of sneaky questions designed to make you second-guess everything. You’ve got this, though! Put on your “I actually know things” hat and crush this quiz—if for no other reason than to prove that Drivers of PED is no match for you. Let’s go!'
    
    chapter21 = db.session.get(Chapter, 21)
    chapter21.video_blurb = 'What do Quentin Tarantino movies and price elasticity of demand have in common? They’re both unapologetically extreme.  If demand for your product is inelastic, you can jack up the price, and people will keep buying—like a Tarantino fan paying for yet another 4K director’s cut of<em>Pulp Fiction</em>, again boosting Total Revenues to Harvey Weinstein. But if your product has elastic demand? Raise the price even a little, and customers scatter faster than moviegoers at the sight of <em>The Hateful Eight</em>. \n\n This video dives into how price elasticity and total revenue play off each other, showing you when to crank up the price and when to leave it alone. It’s a classic Tarantino twist—unexpected, a little bloody (economically speaking), and definitely worth watching. Don’t miss it, and then go prove you’re the star of this show on the quiz!'
    chapter21.quiz_blurb =  'Welcome to the Price Elasticity of Demand and Total Revenue quiz! This is where economics gets real—deciding whether raising prices will boost your revenue or tank it entirely. It’s the classic balancing act: If demand is inelastic, you can squeeze more money out of customers without losing too many sales. But if demand is elastic, even a small price hike could send your revenue into a free fall. \n\n Still feeling unsure? Take a page from Stringer Bell’s playbook in The Wire (Season 3, Episode 11, around the 41-minute mark). Yes, a drug kingpin explains price elasticity better than most textbooks. Watch that scene for some gritty inspiration, then come back and crush this quiz. Let’s see if you’ve got what it takes to master the market!'
    
    chapter22 = db.session.get(Chapter, 22)
    chapter22.video_blurb = 'Cross-price elasticity of demand—abbreviated XED—because everything with the letter X is automatically cooler. Almost everything, anyway. (If you just thought of something that isn’t, don’t blame us. You technically can’t sue for disappointment.) XED is all about how the price of one good impacts the demand for another. Substitutes, complements, frenemies—it’s a whole drama. \n\n Here’s the video that breaks it all down without the legal disclaimers. Watch it, soak it in, and get ready to ace the quiz. XED might not be as cool as X-Men: The Animated Series, but it’s way more useful when you’re buying coffee and bagels.'
    chapter22.quiz_blurb = 'Welcome to the cross-price elasticity of demand quiz, where you get to figure out how the price change of one product messes with the demand for another. That’s right, it’s like the butterfly effect for stuff you buy. When the price of something goes up, sometimes people switch to something cheaper (substitutes), or they buy less of something they usually pair it with (complements). Classic economics. \n\n For example, if the price of almond milk goes up, suddenly people are grabbing oat milk like it’s going out of style—because apparently, we’re all just one price hike away from switching our entire beverage identity. That’s substitutes in action.  Or when the price of movie tickets goes up, demeand for movie popcorn falls because people realize they’d rather keep their dignity than pay $28 for a feed-bag sized bucket of popped corn and liquid heart-disease.  That’s complements baby.  Now get ready to flex your econ knowledge. This isn’t rocket science, but it’s probably more useful than whatever trend you’re following on TikTok right now.'
    
    chapter23 = db.session.get(Chapter, 23)
    chapter23.video_blurb = 'Welcome to the video on income elasticity of demand, where we dive into how changes in your income affect what you buy. Spoiler: when you get that raise, you might suddenly splurge on fancy shoes, or if you don’t hit your sales target for the month, you’ll go for the store-brand cereal and pretend it’s just as good as that of Tony the Tiger’s. \n\n This isn’t just about what you want—it’s about how the stuff you <em>need</em> (or <em>think</em> you need) changes depending on how much cash you have flowing in and available to burn. Watch the video to see how changes to your income might make you a high roller one day and a bargain hunter the next. us, you’ll definitely impress everyone when you explain why you’re ditching instant noodles for sushi after that bonus—because nothing says "I’ve got my life together" like overpriced fish.'
    chapter23.quiz_blurb = 'Welcome to the income elasticty of demand quiz.  Imagine winning the lottery and then having to awkwardly explain why you’re buying <em>more</em> Pabst Blue Ribbon and not craft beer.  This is all about how your spending changes when your income takes a hit -- or, for once, when it actually <em>increases</em> (don’t get used to it). Spoiler: more money might mean fewer ramen noodles, or maybe you’ll buy the same amount and just feel fancy about it. \n\n You’re almost done with this unit, so don’t screw it up now. Remember, you can’t buy a Ferrari with quiz answers, but at least you’ll understand why you might spend less on Taco Bell after a big raise. Keep going—this is almost over.'
    
    chapter24 = db.session.get(Chapter, 24)
    chapter24.video_blurb = 'Welcome to the price elasticity of supply video, where we talk about how suppliers, like Gus Fring and his Los Pollos Hermanos, react when prices go up. When the price of chicken rises, Gus is definitely going to want to crank out more wings, but he’s not just slinging more buckets of chicken on the street corner. He’s thinking about capacity, quality, and whether he needs a few more trucks on the road to meet demand—without drawing too much attention. \n\n Watch the video to see how suppliers make their moves, just like Gus does with his “business”—always calculating how much more he can supply without blowing his cover. It’s not just about more, it’s about more <em>strategically</em>—and maybe avoiding a few explosions along the way.'
    chapter24.quiz_blurb = 'Congrats, you’ve made it to the price elasticity of supply quiz! This is the last stretch, so just ace this and get it over with. Finally, you’re free to move on to greener pastures—or at least pretend you’re excited about whatever’s next. Holy [insert appropriate expletive], that was painful, but hey, if you’re one of the few that loved it, we’re all proud of you. \n\n You’re almost done, so don’t blow it now. One more quiz, and you’ll be officially free from the grasp of elasticity. Keep going, and show us what you’ve got.'

    db.session.commit()


def main():
    with app.app_context():
        seed_blurbs()

if __name__=="__main__":
    try:
        main()
    except IntegrityError:
        db.session.rollback()
        print("There was an error seeding the database")


