"""empty message

Revision ID: 033de9ff1fa0
Revises: 384c7795b380
Create Date: 2024-12-06 10:31:34.715732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033de9ff1fa0'
down_revision = '384c7795b380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('testing')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testing', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
