"""add unique constraint on user_id and chapter_id

Revision ID: 09ac75f32178
Revises: 18af0f62efe8
Create Date: 2024-09-05 14:09:31.886632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ac75f32178'
down_revision = '18af0f62efe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chapter_progress', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_chapter', ['user_id', 'chapter_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chapter_progress', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_chapter', type_='unique')

    # ### end Alembic commands ###
