"""add video_blurb and quiz_blurb to Chapter

Revision ID: 0b32e2b9e376
Revises: 09ac75f32178
Create Date: 2024-09-18 10:27:17.773377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b32e2b9e376'
down_revision = '09ac75f32178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_blurb', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quiz_blurb', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('quiz_blurb')
        batch_op.drop_column('video_blurb')

    # ### end Alembic commands ###
