"""empty message

Revision ID: 0b7d2fcce2d1
Revises: 1318a15852da
Create Date: 2025-01-22 14:14:57.684018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b7d2fcce2d1'
down_revision = '1318a15852da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_video_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=True)
        batch_op.drop_column('short_video_url')

    # ### end Alembic commands ###
