"""add column types

Revision ID: 384c7795b380
Revises: 94d0a4767d9f
Create Date: 2024-12-06 10:30:05.185837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384c7795b380'
down_revision = '94d0a4767d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testing', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('testing')

    # ### end Alembic commands ###
