"""try

Revision ID: 3d560c34babd
Revises: 1ece694944f5
Create Date: 2024-08-30 09:01:13.336845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d560c34babd'
down_revision = '1ece694944f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_performance', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_performance', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
