"""Add quiz image url to chapter

Revision ID: 60407442eb52
Revises: 64e85e4c61b6
Create Date: 2024-11-08 08:57:30.469527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60407442eb52'
down_revision = '64e85e4c61b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_blurb_img_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('quiz_blurb_img_url')

    # ### end Alembic commands ###
