"""add active bool to progress

Revision ID: 64e85e4c61b6
Revises: 562e26f20306
Create Date: 2024-10-24 12:51:36.627525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e85e4c61b6'
down_revision = '562e26f20306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chapter_progress', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
