"""empty message

Revision ID: 747df35cef47
Revises: d14388bbe46f
Create Date: 2024-09-03 08:55:15.405535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747df35cef47'
down_revision = 'd14388bbe46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('video_completed', sa.Boolean(), nullable=False),
    sa.Column('quiz_grade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_video_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_video_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name='user_video_progress_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_video_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_video_progress_pkey')
    )
    op.drop_table('user_chapter_progress')
    # ### end Alembic commands ###
