"""empty message

Revision ID: 841080d176af
Revises: c37d80f326de
Create Date: 2024-09-01 20:19:54.559982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '841080d176af'
down_revision = 'c37d80f326de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_video_progress', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_video_progress', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###
