"""empty message

Revision ID: d14388bbe46f
Revises: 9cf0285e5ca2
Create Date: 2024-09-01 20:26:38.019512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14388bbe46f'
down_revision = '9cf0285e5ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_video_progress', schema=None) as batch_op:
        batch_op.drop_column('video_started')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_video_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_started', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
