"""initial migration

Revision ID: ecff945d6052
Revises: 
Create Date: 2024-12-09 08:47:15.054413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecff945d6052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('video_blurb', sa.Text(), nullable=True),
    sa.Column('quiz_blurb', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('quiz_blurb_img_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='fk_chapter_unit_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('current_chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name='question_chapter_id'),
    sa.ForeignKeyConstraint(['topic_id'], ['question_topic.id'], name='question_topic_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chapter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name='chapter_user_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_chapter_id'),
    sa.PrimaryKeyConstraint('user_id', 'chapter_id')
    )
    op.create_table('user_chapter_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('video_completed', sa.Boolean(), nullable=False),
    sa.Column('quiz_grade', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name='chapter_progress_user_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_chapter_progress_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uix_user_chapter')
    )
    op.create_table('user_topic_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('answered_correctly', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['question_topic.id'], name='topic_progress_user_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_topic_progress_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uix_user_topic')
    )
    op.create_table('user_unit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='unit_user_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_unit_id'),
    sa.PrimaryKeyConstraint('user_id', 'unit_id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='answer_question_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='userperformance_qusetion_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userperformance_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_performance')
    op.drop_table('answer')
    op.drop_table('user_unit')
    op.drop_table('user_topic_progress')
    op.drop_table('user_chapter_progress')
    op.drop_table('user_chapter')
    op.drop_table('question')
    op.drop_table('user')
    op.drop_table('question_topic')
    op.drop_table('chapter')
    op.drop_table('unit')
    op.drop_table('subject')
    # ### end Alembic commands ###
