"""empty message

Revision ID: f1317aa6d67b
Revises: fda01c3a45c8
Create Date: 2024-09-03 10:22:20.218488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1317aa6d67b'
down_revision = 'fda01c3a45c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
